(deftheme badwolf-matt
  "Created 2018-11-06.")

(custom-theme-set-faces
 'badwolf-matt
 '(default ((t (:family "Hack" :foundry "nil" :width normal :height 220 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#f8f6f2" :background "#1c1b1a" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#39ff14"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#0a9dff"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#f8f6f2"))))
 '(highlight ((t (:foreground "#000000" :background "#fade3e"))))
 '(region ((t (:background "#45413b"))))
 '(shadow ((t (:foreground "#666462"))))
 '(secondary-selection ((t (:foreground "#242321" :background "#0a9dff"))))
 '(trailing-whitespace ((t (:foreground "#141413" :background "#ff9eb8"))))
 '(font-lock-builtin-face ((t (:foreground "#f8f6f2"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#998f84"))))
 '(font-lock-comment-face ((t (:foreground "#998f84"))))
 '(font-lock-constant-face ((t (:foreground "#b88853"))))
 '(font-lock-doc-face ((t (:foreground "#f4cf86"))))
 '(font-lock-function-name-face ((t (:foreground "#ffa724"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "#ff2c4b"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#aeee00"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#f4cf86"))))
 '(font-lock-type-face ((t (:foreground "#ff9eb8"))))
 '(font-lock-variable-name-face ((t (:foreground "#ffa724"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#ff9eb8"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#998f84"))))
 '(link-visited ((t (:foreground "#ffa724" :inherit (link)))))
 '(fringe ((t (:background "#1c1b1a"))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:box nil :foreground "#f8f6f2" :background "gray22"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box nil :foreground "#857f78" :background "gray16"))))
 '(isearch ((t (:weight bold :foreground "#000000" :background "#ff9eb8"))))
 '(isearch-fail ((t (:foreground "#ff2c4b" :background "#1c1b1a"))))
 '(lazy-highlight ((t (:foreground "#000000" :background "#fade3e"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'badwolf-matt)
